import { defineCollection, z } from 'astro:content';
import { glob } from 'astro/loaders';

const media = { image: z.string().optional(), video_url: z.string().url().optional() };
const experience = defineCollection({ loader: glob({ pattern: '**/*.{md,yml,yaml}', base: './src/content/experience' }), schema: z.object({ role:z.string(), organization:z.string(), location:z.string().optional(), start_date:z.coerce.date(), end_date:z.union([z.coerce.date(),z.literal('Present')]), bullets:z.array(z.string()).default([]), ...media }) });
const education = defineCollection({ loader: glob({ pattern:'**/*.{md,yml,yaml}', base:'./src/content/education' }), schema:z.object({ degree:z.string(), institution:z.string(), location:z.string().optional(), start_date:z.coerce.date(), end_date:z.coerce.date(), description:z.string().optional(), ...media }) });
const publications = defineCollection({ loader:glob({pattern:'**/*.{md,yml,yaml}',base:'./src/content/publications'}), schema:z.object({ authors:z.string(), title:z.string(), source:z.string(), year:z.number(), link:z.string().url().optional(), tags:z.array(z.string()).default([]), ...media }) });
const grants = defineCollection({ loader:glob({pattern:'**/*.{md,yml,yaml}',base:'./src/content/grants'}), schema:z.object({ title:z.string(), funder:z.string(), amount:z.string().optional(), role:z.string(), start_date:z.coerce.date(), end_date:z.coerce.date(), status:z.string(), description:z.string(), ...media }) });
const awards = defineCollection({ loader:glob({pattern:'**/*.{md,yml,yaml}',base:'./src/content/awards'}), schema:z.object({ title:z.string(), body:z.string(), date:z.coerce.date(), description:z.string(), ...media }) });
const engagements = defineCollection({ loader:glob({pattern:'**/*.{md,yml,yaml}',base:'./src/content/engagements'}), schema:z.object({ title:z.string(), organization:z.string(), date:z.coerce.date(), description:z.string(), ...media }) });
const certifications = defineCollection({ loader:glob({pattern:'**/*.{md,yml,yaml}',base:'./src/content/certifications'}), schema:z.object({ name:z.string(), issuing_body:z.string(), date:z.coerce.date().optional(), link:z.string().url().optional(), ...media }) });
const mediaNews = defineCollection({ loader:glob({pattern:'**/*.{md,yml,yaml}',base:'./src/content/media'}), schema:z.object({ outlet:z.string(), title:z.string(), date:z.coerce.date(), link:z.string().url().optional(), type:z.enum(['TV','Print','Online']), ...media }) });
const ntros = defineCollection({ loader:glob({pattern:'**/*.{md,yml,yaml}',base:'./src/content/ntros'}), schema:z.object({ title:z.string(), type:z.string(), year:z.number(), award_status:z.string().optional(), description:z.string(), collaborators:z.string().optional(), ...media }) });
const specializations = defineCollection({ loader:glob({pattern:'**/*.{md,yml,yaml}',base:'./src/content/specializations'}), schema:z.object({ name:z.string(), rating:z.number().min(1).max(5).optional(), category:z.enum(['Specialization','Competency']).default('Specialization') }) });
const projects = defineCollection({ loader:glob({pattern:'**/*.{md,yml,yaml}',base:'./src/content/projects'}), schema:z.object({ title:z.string(), year:z.number(), summary:z.string(), category:z.string(), featured:z.boolean().default(false), images:z.array(z.string()).default([]), tags:z.array(z.string()).default([]), link:z.string().url().optional(), ...media }) });
const site = defineCollection({ loader:glob({pattern:'**/*.{yml,yaml}',base:'./src/content/settings'}), schema:z.object({ name:z.string(), credentials:z.string(), eyebrow:z.string(), headline:z.string(), introduction:z.string(), professional_profile:z.string(), profile_image:z.string(), profile_image_alt:z.string(), email:z.string().email(), linkedin:z.string().url(), phone:z.string().optional(), location:z.string(), teaching_start_date:z.coerce.date(), teaching_countries:z.array(z.string()).default([]), analytics_id:z.string().optional() }) });
const teaching = defineCollection({ loader:glob({pattern:'**/*.{yml,yaml}',base:'./src/content/teaching'}), schema:z.object({ title:z.string(), quote:z.string(), quote_author:z.string(), introduction:z.string(), sections:z.array(z.object({ title:z.string(), text:z.string() })), image:z.string().optional(), video_url:z.string().url().optional() }) });
const profiles = defineCollection({ loader:glob({pattern:'**/*.{yml,yaml}',base:'./src/content/profiles'}), schema:z.object({ name:z.string(), url:z.string().url(), identifier:z.string().optional(), category:z.enum(['Research profile','Professional membership']) }) });

export const collections = { experience, education, publications, grants, awards, engagements, certifications, media: mediaNews, ntros, specializations, projects, site, teaching, profiles };
